name: Release sample-container-todo-app-java-maven to Docker Hub for lab

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      THUNDRA_LAB_APIKEY:
        required: true
env:
  WORKFLOW_TELEMETRY_BASE_URL: https://api.service.runforesight.me
jobs:
  release:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: tolgatakir/sample-container-todo-app-java-maven
    steps:
      - name: Foresight Workflow Kit Action
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.THUNDRA_LAB_APIKEY }}
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
      - name: Create Artifact
        run: ./mvnw -B clean package -DskipTests
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker Image
        run: docker push $REPO -a
